version: '3.1'
services:
  nextjs:
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3001:3000
    command: bash -c "corepack enable && corepack prepare pnpm@latest --activate && pnpm install && pnpm run dev"