export const runtime = "nodejs";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import "./globals.css";
import { RootProvider } from 'fumadocs-ui/provider';
import GoogleAnalytics from "@/components/google-analytics";

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body>
        <GoogleAnalytics />
        <RootProvider>
          {children}
        </RootProvider>
        </body>
      </html>
  );
}
